### ISSUE TITLE
It doesn't seem to work in Bowser for iOS

### ISSUE THREAD

**Issue by kooler** [EricssonResearch/openwebrtc-examples#10]
I'm trying to initiate a session between Chrome and Bowser (ios). After both devices joined the room I click "Initiate call" but receive an error: "Error processing ICE candidate". Sometimes video stream from iPhone appears for a moment in Chrome, but immediately freezes.

It also doesn't work with http://apprtc.appspot.com.

**Comment by stefanalund** [comment]
If you still have problem, please re-open. I'm closing this issue for now since it seems to work. Please file issues with Bowser here instead: https://github.com/EricssonResearch/bowser
