### ISSUE TITLE
is there any open source STUN and TURN server available?

### ISSUE THREAD

**Issue by jpatel956** [EricssonResearch/openwebrtc-examples#101]
I  have successfully able to test Native Demo. And i am tried to modified same as per our requirement. but i have one confusion that while going to keep my application live, is i need to developer STUN and TURN server at our end? or is there open source server available?. what are the extra step need to make my server live?

Can any one help me

**Comment by superdump** [comment]
There are public stun servers and even some public turn servers that other people run. You can also set up your own and there are existing stun/turn server implementations that you can search the web for. A couple of examples are rfc5766-turn-server and coturn. I believe those will also support stun functionality.

**Comment by jpatel956** [comment]
@superdump thanks.
