### ISSUE TITLE
Preview freeze after iOS hangup

### ISSUE THREAD

**Issue by pauluhn** [EricssonResearch/openwebrtc-examples#106]
After connecting to same room on iOS and chrome, I press hangup on iOS. I join a new room with chrome again. If I call from chrome, I get local and remote video (from iOS) but both previews on iOS are frozen. I get this in console:

```
2015-06-19 09:33:42.519 NativeDemo[2780:1110490] Joining room with ID: 333
[video/capture] Front Camera

** (<unknown>:2780): CRITICAL **: _owr_window_registry_register_renderer: assertion '!data->renderer' failed
[video/capture] Back Camera
[audio/capture] Default audio input
2015-06-19 09:33:42.524 NativeDemo[2780:1110544] gotLocalSourcesWithNames: (
    "Front Camera",
    "Back Camera",
    "Default audio input"
)

** (<unknown>:2780): CRITICAL **: on_component_state_changed: assertion 'OWR_IS_TRANSPORT_AGENT(transport_agent)' failed
2015-06-19 09:33:55.916 NativeDemo[2780:1110490] peer <979f7b33> joinedRoom: 333
```

**Comment by tobi512** [comment]
I have noticed the same behavior. The freeze doesn't affect the video-transmission to the other side for me, its just the local preview of the devices camera. 
Only solution I found for now is killing the app, so a proper solution would be very welcome!

**Comment by tobi512** [comment]
@pauluhn Not sure if its the proper way, but i made a workaround by commenting out the
`owr_window_registry_unregister(owr_window_registry_get(), SELF_VIEW_TAG);` and `owr_window_registry_unregister(owr_window_registry_get(), REMOTE_VIEW_TAG);`
in `reset()` method of the OpenWebRTCNativeHandler.m (line 984 and 985) from the iOS-SDK, which fixed the freezing preview. 

Seems like somehow they are not properly reregistered after `reset()` was called once...

**Comment by stefanalund** [comment]
Do you feel that this workaround something that could be made into a permanent fix for the problem? What kind of side effects, if any, does it have?

**Comment by tobi512** [comment]
Hi @stefanalund, 
no real side-effects so far, the only thing that changed is that the camera preview is showing live-picture all the time after the first room-join. Previously is was shut down after hangup but didnt get properly reattached when joining again. 

I'm not an expert in the workflow of OWR, you think my workaround could have side-effects on the battey life as the camera is always in use?

**Comment by stefanalund** [comment]
Yes it will, but it sounds like a better solution than a frozen video. Would appreciate a Pull Request if you have the possibility! Thanks.

**Comment by tobi512** [comment]
@stefanalund PR ready to be merged...

**Comment by stefanalund** [comment]
Merged. Thanks!
