### ISSUE TITLE
Android native call client doesn't work even with live demo on your page

### ISSUE THREAD

**Issue by onlyway** [EricssonResearch/openwebrtc-examples#117]
I've build demo app on my Androide device (nexus 5 with android 5.1). When I'mt trying to establish connection between your demo (http://demo.openwebrtc.org:38080) i have such errors:

Failed to set local sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set video send codecs..

Failed to set remote sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set video send codecs..

Errors shows up on demo web page under place for video. 

Where is the problem?

**Comment by carterbryden** [comment]
Getting the same after reverting to baedd75204 as advised in issue #114 when we try to do android to chrome.

**Comment by superdump** [comment]
@Rugvip

**Comment by onlyway** [comment]
Strange, today I've checked the same version of Android app on your server and it works. On my server unfortunatly not. Did you make any changes on web version?

**Comment by stefanalund** [comment]
No changes on our side.

**Comment by superdump** [comment]
I don't think there are local changes on demo.openwebrtc.org but it is running an older version of the web code.

Specifically https://github.com/EricssonResearch/openwebrtc-examples/commit/8f7b847b5f2d0a267ef1eaea5f8b2f405af6a120 seems to require some changes to client apps that we have not yet done. If you revert just that commit on master then it should work.

**Comment by onlyway** [comment]
Ok I've combined JS files from commit you said and from your demo page. And now it is working like a charm :)
