### ISSUE TITLE
[iOS] NativeDemo - #include "owr.h" "owr.h" file not found

### ISSUE THREAD

**Issue by pbserious** [EricssonResearch/openwebrtc-examples#123]
Hello, 

I have cloned the example project from https://github.com/EricssonResearch/openwebrtc-examples

I have "pod install" already in NativeDemo, open NativeDemo.xcworkspace with Xcode

But when I build&run the project on my iPhone I always got error at OpenWebRTCNavtiveHandler.m "owr.h" file not found

![screen shot 2558-09-16 at 5 38 55 pm](https://cloud.githubusercontent.com/assets/14310862/9902592/d7a4a344-5c99-11e5-89ee-85222353f0e5.png)

I have tried in my simple project by pod install OpenWebRTC-SDK but I got the same error.

I searched for the related old/closed issue but I got no clue.(Sorry if this issue is duplicated)

I also manually built OpenWebRTC and It's work fine with the SimpleDemo 

How can i fix this error? or Did I miss some steps?
I really want to try the NativeDemo project 

Thanks in advance

**Comment by stefanalund** [comment]
The OpenWebRTC-SDK is not yet hosted in the official pod repo, you need to download it separately and put as a "local" pod. More information is available on the wiki: https://github.com/EricssonResearch/openwebrtc-examples/wiki/Developing-a-native-iOS-app

**Comment by pbserious** [comment]
@stefanalund  Thanks for your quick response 

I already have cloned "openwebrtc-ios-sdk" in "NativeDemo" folder 
I did the local pod with  ":path" to OpenWebRTC-SDK.podspec in my Podfile. But this error still persist. 

Does it necessary to put "openwebrtc-ios-sdk" folder next to "NativeDemo" folder?

**Comment by stefanalund** [comment]
Yes, they need to be on the same level.

**Comment by stefanalund** [comment]
Wait...did you also install the pod called "OpenWebRTC"?

**Comment by pbserious** [comment]
I solved it finally.

My setup and configurations are correct with every step in the wiki. But the cause of the problem is I had use Cocoapods pre release version (0.39 pre) after I uninstalled the pre version and install the stable one (0.38.2) everything works fine.

Thanks for your support @stefanalund

**Comment by stefanalund** [comment]
Nice!
