### ISSUE TITLE
Datachannel supported in iOS?

### ISSUE THREAD

**Issue by vanney9** [EricssonResearch/openwebrtc-examples#135]
Does OpenWebRTC supported datachannel in iOS; and if it supported, is there any demo to show how to use datachannel in iOS?

**Comment by stefanalund** [comment]
Yes. OpenWebRTC has two sets of APIs, JavaScript and native (C API). DataChannel implemented in the JavaScript domain can be tested in Bowser (see http://www.openwebrtc.org/blog/2015/3/4/now-with-100-more-data-channel-support). However, we currently do not have a native example app showing how to use the C API.
