### ISSUE TITLE
ios_native_demo: Video Mode Error / dedicate server

### ISSUE THREAD

**Issue by zing1911** [EricssonResearch/openwebrtc-examples#137]
Hi I'm newbie for this one

I'm try your sample and I have questions ?
1. How to change VideoMode without Error ? I've changed VideoMode From 'VGA' to 'QVGA' 
it's error occur like below 
...........
2015-11-12 09:58:52.595 NativeDemo[1029:240425] [OpenWebRTC] initialized correctly!
2015-11-12 09:58:52.935 NativeDemo[1029:240425] Video settings: {
    bitrate = 1024000;
    framerate = 25;
    height = 240;
    mode = QVGA;
    width = 320;
}
2015-11-12 09:58:53.235 NativeDemo[1029:240425] Can't find keyplane that supports type 4 for keyboard iPhone-Portrait-NumberPad; using 1730230351_Portrait_iPhone-Simple-Pad_Default
2015-11-12 09:58:53.284 NativeDemo[1029:240425] [OpenWebRTC] Setting video rotation to: -90

(<unknown>:1029): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed
2015-11-12 09:58:57.022 NativeDemo[1029:240425] Joining room with ID: 147
[video/capture] Front Camera
[video/capture] Back Camera
[audio/capture] Default audio input
2015-11-12 09:58:57.115 NativeDemo[1029:240457] gotLocalSources: (
        {
        mediaType = video;
        name = "Front Camera";
        source = "<105acf01 01000000>";
    },
        {
        mediaType = video;
        name = "Back Camera";
        source = "<a059cf01 01000000>";
    },
        {
        mediaType = audio;
        name = "Default audio input";
        source = "<805acf01 01000000>";
    }
)
2015-11-12 09:58:57.115 NativeDemo[1029:240457] Found cameras: (
    "Front Camera",
    "Back Camera"
)
2015-11-12 09:58:57.116 NativeDemo[1029:240457] [OpenWebRTC] Setting video rotation to: 0
0:00:04.641559000 [334m 1029[00m    0x101ce3070 [31;01mERROR  [00m [00m owrlocalmediasource owr_local_media_source.c:645:owr_local_media_source_request_source:[00m Failed to link source -> capsfilter
==== Error message start ====
Error in element video-source.
Error: Internal data flow error.
Debugging info: gstbasesrc.c(2943): void gst_base_src_loop(GstPad *) (): /GstPipeline:local-video-capture-source-bin-0/GstAVFVideoSrc:video-source:
streaming task paused, reason not-linked (-1)
==== Error message stop ====

.....................

2. I would like to set own dedicate server for this project because I usually got disconnected error and voice lag when I've tested on your default url. How I can set STUN, TURN or other server for using with your API. please suggest me 

Thank you very much

**Comment by xelven** [comment]
Probably the source can not be 320/240, I am not sure about it.
try to change 352/288 CIF  or comment code as below in VideoAttributes.m:

modesDictionary = @{@"QCIF":@[@"176", @"144"],
                            @"QVGA":@[@"320", @"240"],
                            @"CIF":@[@"352", @"288"],
                            @"360p":@[@"640", @"360"],
                            //@"VGA":@[@"640", @"480"],
                            @"VGA":@[@"352", @"288"],
                            @"720p":@[@"1280", @"720"],
                            @"1080p":@[@"1920", @"1080"]};


it's work for me

**Comment by zing1911** [comment]
@xelven  Thank you It's work for me too !  solved No.1 question

**Comment by stefanalund** [comment]
Great. Would be appreciated if you would create a Pull Request with your changes.

One good option for a TURN server is coturn https://github.com/coturn/coturn As TURN servers also implement STUN, coturn would be sufficient.
