### ISSUE TITLE
Linker Command error on Xcode 7.1.1

### ISSUE THREAD

**Issue by hansimmmi** [EricssonResearch/openwebrtc-examples#141]
Hi! I'm new to OpenWebRTC, it's been a whole day to figure out what to do. 
I finally get to the point to downgrade cocoa pods to 0.38.2 and use local pod spec to fix "owr.h is not found" issue. 
But I have linker command error as following. My head is about to blow off, let me know if you guys need more info.  

all project, NativeDemo, Selfie, SimpleDemo, or even my test project have same issue. 
These 2 are the pod successfully installed. 
OpenWebRTC (0.3.90)
OpenWebRTC-SDK (0.3.2)

![screen shot 2015-11-16 at 8 29 28 pm](https://cloud.githubusercontent.com/assets/7344606/11202791/dcb2a84a-8ca0-11e5-8233-7949d7148488.png)

**Comment by stefanalund** [comment]
You need to manually add the External Library `libiconv` to the build step.

**Comment by stefanalund** [comment]
<img width="1340" alt="image" src="https://cloud.githubusercontent.com/assets/190856/11203118/a745cc14-8cf0-11e5-84f4-e4a1cb9065f4.png">
