### ISSUE TITLE
SSL on demo.openwebrtc.org

### ISSUE THREAD

**Issue by virorum** [EricssonResearch/openwebrtc-examples#146]
Possibly not the right place to raise this but...

Now that Chrome requires HTTPS for getUserMedia() are there plans to add SSL to the demo site?

**Comment by superdump** [comment]
This is on my todo list for this week.

**Comment by nevyn** [comment]
The demo site seems to be down completely now?

**Comment by stefanalund** [comment]
@nevyn the site is now back up. Sorry for the inconvenience.

**Comment by nevyn** [comment]
@stefanalund Thanks! I can't make it work over http even with overrides though, so would also appreciate SSL. I hear letsencrypt is nice :3

**Comment by stefanalund** [comment]
You mean in Chrome or elsewhere as well?

**Comment by stefanalund** [comment]
First step taken: https://github.com/EricssonResearch/openwebrtc-examples/pull/182

**Comment by superdump** [comment]
Now live at https://demo.openwebrtc.org : https://twitter.com/openwebrtc/status/727491243089993733
