### ISSUE TITLE
NativeDemo builds on simulator, but fails on device

### ISSUE THREAD

**Issue by mjrock** [EricssonResearch/openwebrtc-examples#149]
Please help - the NativeDemo project will compile on every simulator, but does not actually build properly when pushing to a device (Error code: 'linker command failed with exit code 1 (use -v to see invocation)'). I'm running on ios 9.2 on iphone 4s.

**Comment by stefanalund** [comment]
Could you provide some more info and/or screenshots?

**Comment by mjrock** [comment]
![screen shot 2015-12-27 at 8 46 33 pm](https://cloud.githubusercontent.com/assets/16455433/12013031/073398a4-acdb-11e5-88a5-32f11c6a5e2d.png)

Every simulator will build and run, but I get this error when trying to push to my iphone 4S and the iPad mini.

**Comment by stefanalund** [comment]
You need to disable bitcode, see http://stackoverflow.com/questions/30848208/new-warnings-in-ios9

This should have been done already though. Are you using the latest NativeDemo? Thanks.

**Comment by mjrock** [comment]
I am using the latest NativeDemo. I have disabled bitcode as per you recommendation and am now able to push to my device. Now I can't enable audio without crashing the app on my device, but think I saw something about this in another issue thread.
Thank you very much for your help.
Cheers,
Mike

**Comment by stefanalund** [comment]
Could you please make a Pull Request with your change? It may be that bitcode needs to be disabled per architecture (arm7 in this case). Thanks.
