### ISSUE TITLE
Cocoapod for OpenWebRTC down?

### ISSUE THREAD

**Issue by Reedyuk** [EricssonResearch/openwebrtc-examples#156]
When doing pod update i am getting an error: 
Failed to connect to static.verkstad.net port 80: Operation timed out
Its unable to get the webrtc zip file: http://static.verkstad.net/OpenWebRTC_0.3.94.zip

**Comment by stefanalund** [comment]
We have had a HW failure on that machine that serves those files. We are working on getting it up again.

**Comment by haichuand** [comment]
I'm getting the same error. Is the server up now?

**Comment by stefanalund** [comment]
A new version 0.3.95 is now available from a new server, please try running `pod install` again.
