### ISSUE TITLE
pod install error   !!!!!!!!!!

### ISSUE THREAD

**Issue by liwuking** [EricssonResearch/openwebrtc-examples#164]
yuke:NativeDemo imacli$ pod install
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OpenWebRTC-SDK` from `https://github.com/EricssonResearch/openwebrtc-ios-sdk.git`, commit `34a382f235c673562fe137f4fea427a17dbb8d97`
Downloading dependencies
Installing InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.3.1)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/7v/x1vx6g4s3xx9vfhzrsxw5g8h0000gn/T/d20160303-3119-7u74h2/file.zip http://static.verkstad.net/OpenWebRTC_0.3.1.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to static.verkstad.net port 80: Connection refused

**Comment by stefanalund** [comment]
See https://github.com/EricssonResearch/openwebrtc-ios-sdk/issues/61.

**Comment by liwuking** [comment]
@stefanalund   
yuke:NativeDemo imacli$ rm -rf Pods Podfile.lock && pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OpenWebRTC-SDK` from `https://github.com/EricssonResearch/openwebrtc-ios-sdk.git`
Downloading dependencies
Installing InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.3.95)

[!] Error installing OpenWebRTC
[!] /usr/bin/curl -f -L -o /var/folders/7v/x1vx6g4s3xx9vfhzrsxw5g8h0000gn/T/d20160303-4055-6mpj5j/file.zip https://pods.cct.ericsson.net/OpenWebRTC_0.3.95.zip --create-dirs

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 76  161M   76  123M    0     0   152k      0  0:18:05  0:13:47  0:04:18  162kcurl: (56) SSLRead() return error -36
