### ISSUE TITLE
 OpenWebRTC SDK without Pod...

### ISSUE THREAD

**Issue by sibineshMc** [EricssonResearch/openwebrtc-examples#197]
I need an integration support to openwebrtc with out pod file . I can't able to integrate pod file to existing project .I have to create a video call iOS app with openwebRTC. I can't able to integrate pod file to existing project .Is there OpenwebRTC SDK with out POD support

**Comment by stefanalund** [comment]
See https://github.com/EricssonResearch/openwebrtc-ios-sdk/issues/74
