### ISSUE TITLE
Linux demo or exemple ?

### ISSUE THREAD

**Issue by pigeonvictor** [EricssonResearch/openwebrtc-examples#217]
Hi guys,

I'm working on a projet in which I want to stream the desktop (linux for now) of a computer to a web application.
OpenWebRTC seams to be the right tool to do this but I'm not totally sure.
Is it possible to stream a from a linux client to an other linux client ? From a linux client to a web application ?

Is there any simple exemple or demo including a linux client ?

**Comment by stefanalund** [comment]
Have a look at this one:

https://github.com/EricssonResearch/openwebrtc/blob/master/tests/test_client.c
