### ISSUE TITLE
Native example app for iOS that works with http://demo.openwebrtc.io

### ISSUE THREAD

**Issue by jrosssavant** [EricssonResearch/openwebrtc-examples#28]
I was able to download and build the OpenWebRTC libraries, and build and run the iOS Selfie and SimpleDemo apps.  I'm interested to develop an app that includes OpenWebRTC, but I want to avoid using a WebView and the bridge.   Can you give me a few pointers for how to get started with a full native implementation beyond the Selfie app?

Thanks,
Joe

**Comment by stefanalund** [comment]
I've asked @Rugvip to also have a look at making a version of the native app for iOS. Please let us know @jrosssavant if you have made in progress so that we can avoid double work. Thanks.

**Comment by jrosssavant** [comment]
No, I never made it very far on this.  I ran into a few stumbling blocks early on and then had my priorities pulled away.  However, we're still interested in the iOS native app.  I encourage you to push commits as you go and I'll keep my eye on them and contribute as I can.  Thanks!

**Comment by stefanalund** [comment]
We will be sure to keep you in the loop!

**Comment by jrosssavant** [comment]
Alright, my other priorities have cleared up and I'm back to looking at this.  I'm in the process of syncing and rebuilding recent changes:  would it be best for me to work based on the openwebrtc master branch and build instructions from the wiki, or should I use the nirbheek/cerbero openwebrtc branch?

**Comment by stefanalund** [comment]
As new apps submitted to the App Store from now on requires 64-bit support, I would recommend start using the Cerbero build system as 64-bit is supported:

https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC-with-Cerbero

**Comment by jrosssavant** [comment]
Thanks, using cerbero worked great for me.  Now that I've got the Android native call app working per #31, I'm starting to look at how to apply this to iOS.  It seems pretty straightforward, but one thing I'm realizing is that working with the C APIs is a little awkward and I'm wanting to wrap each C object in an Obj-C object.  This works but is time-consuming, and I'm maintaining a C -> Obj-C map so that I can forward C callbacks to the appropriate Obj-C object.  

Have you considered offering an Obj-C wrapper layer?  I haven't dug into the details of how the Java binding works, but I hope it might be possible to do something similar for Obj-C.

**Comment by stefanalund** [comment]
To be clear, this is because you are using Swift, right?

**Comment by stefanalund** [comment]
This test app in C might also be a useful reference https://github.com/EricssonResearch/openwebrtc/pull/129

**Comment by jrosssavant** [comment]
My application uses Obj-C and Swift.  Integrating a C implementation is certainly possible, and that sample app you linked is very helpful.  But it'd be nicer for iOS devs if there was an Obj-C or Swift interface.  The main thing I want to avoid is jumping between two memory management schemes.

**Comment by stefanalund** [comment]
I certainly agree that would be better, especially as more and more developers adopt Swift in their apps. We will put that on the backlog.

**Comment by stefanalund** [comment]
I have started working on this again and have a WIP skeleton for an app here: https://github.com/EricssonResearch/openwebrtc-examples/pull/49

**Comment by loebpaul** [comment]
Hi @stefanalund, I've been following this development closely. Is there any update to the progress on the Objective-C bridge? Thanks!

**Comment by stefanalund** [comment]
Working on it now, hope to have a working app end of next week.

**Comment by loebpaul** [comment]
amazing, thanks for the update!

**Comment by stefanalund** [comment]
@loebpaul there is a work-in-progress PR that you can follow here: https://github.com/EricssonResearch/openwebrtc-examples/pull/49

**Comment by stefanalund** [comment]
A first version of the NativeDemo app has now landed: https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios/NativeDemo

Still a lot of minor things that should be fixed in the app, such as properly handling rotation, but let's open new Issues for those. Feel free to pick this up and make improvements! :)

**Comment by sentiasa** [comment]
Thanks for the NativeDemo. It seems brilliant. I was wondering, if I convert the whole code to Swift, will it work as it is now or it may crash because of OpenWebRTC-iOS-SDK? Or are you planning to create another example on Swift too?

**Comment by superdump** [comment]
You basically need to wrap all of the OpenWebRTC C API to Objective-C and then bridge that to Swift or something as I recall. Alternatively, perhaps that could be done for the iOS SDK API only, but I'm not sure if that is sufficient. @Rugvip @stefanalund ?

**Comment by stefanalund** [comment]
@sentiasa creating a version in Swift is not on our immediate todo list, even though it would be nice to have it. I don't expect any problems using the iOS SDK from Swift. It would be really awesome if you tried and contributed back the result :smiley:

**Comment by zhangguoyong** [comment]
@sentiasa   if the NativeDemo  Support multiplayer video conferencing ，thanks

**Comment by zhangguoyong** [comment]
Hello everyone，I recently made webRTC multiplayer video, Who used to multiplayer video，And  can give me  a demo, thank you very much。
