### ISSUE TITLE
iOS example applications should be easy to run on the simulator or device

### ISSUE THREAD

**Issue by jrosssavant** [EricssonResearch/openwebrtc-examples#30]
The current example projects will run only on the device, due to the way that the libraries are linked.  Since the armv7 and i386 libraries have the same filenames, the linker just picks one set to link against, and this fails for i386.  

The best way to resolve this issue would be to assemble the libraries into a .framework - a single fat binary containing all libraries for armv7 and i386 and the header files from include/owr.  This could be added as a script in the example apps, but it would be better if this were part of the formal build process for iOS.

**Comment by stefanalund** [comment]
Great to hear Joe.

**Comment by stefanalund** [comment]
Getting closer, building with Cerbero allows you to run in Simulator. I will soon update all demo apps to start using OpenWebRTC.framework (as generated by Cerbero).

![screen shot 2015-02-13 at 15 18 23](https://cloud.githubusercontent.com/assets/190856/6188647/b910a680-b393-11e4-8949-cfc2fb1b56e6.png)

**Comment by arslanraza** [comment]
@stefanalund 
Any update on this issue. I am not able to run my project on any simulator other than iPhone 5.

**Comment by stefanalund** [comment]
Do you mean that it works in the iPhone 5 simulator but not in others?

**Comment by arslanraza** [comment]
@stefanalund 
Yes that is my point.

**Comment by stefanalund** [comment]
As of iOS SDK version 0.3.90 it is now possible to run NativeDemo and other apps in the simulator. There is an error when [running audio](https://github.com/EricssonResearch/openwebrtc-examples/issues/126) but video works:

<img width="432" alt="screen shot 2015-11-15 at 19 10 55" src="https://cloud.githubusercontent.com/assets/190856/11170270/6b66f41a-8bcf-11e5-8b8d-8953ce86b455.png">

Closing this issue.

**Comment by SrujithPoondla** [comment]
Any one how to change the prefix as mentioned in the comment by @sdroege  coulld you please tell the procedure in steps

Thanks

**Comment by superdump** [comment]
@SrujithPoondla - this issue has been fixed for some time and it's not clear what you mean.
