### ISSUE TITLE
IOS selfie app shows only 1 FPS..how to change it?

### ISSUE THREAD

**Issue by Tonku** [EricssonResearch/openwebrtc-examples#34]
Hi,
I have tried the Selfie IOS example, it works fine..except a few issues,

1, The frame rate is only 1 FPS
2,There is no way to show the preview in correct orientation, how it shows horizontal

Also I am wondering I can add the video of remote user just like the same way..?

Kind Regards
Tonku

**Comment by Tonku** [comment]
Hi thanks for input guys..,

I have updated the code and the frame rate has improved... here are the results in 2 devices...
The FPS is varying and as FPS improves CPU increases as well
iPhone5 - 10 to 20 FPS CPU 20 -42%  

iPhone 6 - 5-20FPS CPU 15 -40%

I think the current numbers can be improved...a bit more.

Is there any media hook in the GStreamer which can be accessed via OWR interface.. so that we can replace capture and  display  IOS using alternatives to plain openGL (AVCapturePreviewLayer for preview) and supply with h264 encoded outbound stream to the media channel. similarly we can do it for decoding and rendering h264 inbound stream  using native capability.Since as you guys said, WEBRTC in devices will be more of Apps rather than web , Apps can do a lot more on media than web

Media hook also help to develop other data channels for custom media formats like desktop sharing etc...

Cheers
Tonku

**Comment by stefanalund** [comment]
Still, something is not correct. Maybe @superdump's updated app fixes the suboptimal fps. I'll let someone else answer the question about using alternatives to OpenGL. Perhaps @sdroege knows.

**Comment by Tonku** [comment]
Thanks @stefanalund ...

**Comment by superdump** [comment]
@Tonku - I am updating everything locally and will test this a bit later on my iPhone 6 Plus. How are you measuring the framerate?

**Comment by Tonku** [comment]
Hi @superdump  - I am not sure the way I am checking the frame rate is correct..I use just the xcode profiler to check FPS , here the screen shot of iPhone 6

https://www.dropbox.com/s/qlyymr6r7aiewjy/Screenshot%202015-01-05%2019.08.51.png?dl=0

**Comment by superdump** [comment]
On my iPhone 6 Plus I get between 42 and 60fps depending on where I point the camera in this dark room. I noticed that the frame rate clearly drops down to the lower end of that range when it is adjusting focus or white balance. If the lighting is OK and the camera is quite still (these seemed to affect things) then I could get it to be quite stable at 60fps.

**Comment by Tonku** [comment]
What color space is using currently using.. YUV may give better performance than BGRA ...

**Comment by superdump** [comment]
We take care of all of that efficiently. The video is captured from the camera in its native colour space (I believe it is UYVY but I am not certain) and then in the Selfie app, the colour space conversion to BGRA is done in the GStreamer glimagesink video renderer element which uses an OpenGL shader to do the colour space conversion. Or it should be.

I just tested a modified version of the Selfie app that I will be pushing up for review soon that allows you to switch between the front and back cameras. In that I can see that the front facing camera is much much worse at handling low-light conditions than the back camera. The frame rate with the front facing camera would drop to 7-9 fps quite easily and I am sitting next to a light although the background was dark. I had to hold the front-facing camera a few centimetres from a light bulb and point it directly at the bulb for it to capture at 60 fps.

My conclusion is that there is probably no issue here apart from the cameras and lighting conditions. However, I will take a quick look at the CPU usage to see if there's anything being done there that should not be.

**Comment by superdump** [comment]
Argh. I accidentally built my dependencies using release mode so I have no symbols in the profiler. I'll have to take another look at that later/Wednesday.

**Comment by stefanalund** [comment]
Here's the PR for reference https://github.com/EricssonResearch/openwebrtc-examples/pull/36

**Comment by stefanalund** [comment]
With the latest code from both OpenWebRTC and @superdump's (landed) update to the Selfie I great framerate in good lighting conditions (reduced in poor lighting) on my iPhone 5s:

![screen shot 2015-01-12 at 20 31 28](https://cloud.githubusercontent.com/assets/190856/5709422/1133af46-9a9a-11e4-8cf3-6da74ad9dd5e.png)

I'll close this issue. If the problem persists, please reopen it.

Thanks for you help debugging this. Let us know if we can assist further.
