### ISSUE TITLE
No podspec found for `OpenWebRTC` 

### ISSUE THREAD

**Issue by KerwinMa** [EricssonResearch/openwebrtc-examples#66]
usr/bin/pod install

Analyzing dependencies
Fetching podspec for `OpenWebRTC` from `../../../openwebrtc-ios-sdk/OpenWebRTC.podspec`
[!] No podspec found for `OpenWebRTC` in `../../../openwebrtc-ios-sdk/OpenWebRTC.podspec`

Not able to compile IOS Native. Pls advise, I have the ios-sdk in the right folder.

**Comment by stefanalund** [comment]
You can try to change the Podfile to:

`pod 'OpenWebRTC'`

That should downloaded the 0.1.1 release. 

We are still figuring out how to use CocoaPods for the distribution of OpenWebRTC, sorry about the inconvenience.

**Comment by stefanalund** [comment]
@KerwinMa did that help? Please check your local relative path. I just tried integrating the local OpenWebRTC-SDK.podspec in to a new app and had to change the relative path.

**Comment by stefanalund** [comment]
Nice! Note that I made some changes to the podspecs yesterday, so you may need to pull in the latest from master.

**Comment by KerwinMa** [comment]
@stefanalund, sorry for the late response. I pulled the latest and works fine now. Thanks for the great work.

**Comment by stefanalund** [comment]
Nice! Let us know if you have any other questions.
