### ISSUE TITLE
None of ios projects can work correctly!!!!

### ISSUE THREAD

**Issue by lennondong** [EricssonResearch/openwebrtc-examples#78]
What's wrong with all the ios projects? They can't running at all.
if you using pod update ,there'll be errors.

**Comment by superdump** [comment]
Interesting. I tested all of the iOS applications yesterday, apart from Bowser. All of them are functional and build for me. Do you have specific problems you can report?

**Comment by lennondong** [comment]
SimpleDemo，download it and just open it. Here's the error:

Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

![snip20150423_1](https://cloud.githubusercontent.com/assets/3203702/7297338/8c8c6200-e9fa-11e4-8c18-bc5b9bb6d223.png)


NativeDemo

After finishing pod install and run ...

ld: library not found for -lPods-NativeDemo-InAppSettingsKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by superdump** [comment]
SimpleDemo doesn't use cocoapods yet, as far as I can see. Did you build the OpenWebRTC framework according to https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC ?

For NativeDemo, I think if you remove the `Podfile.lock` file and then run `pod install` and check that it succeeds. Then open the `NativeDemo.xcworkspace` file with Xcode, that should work.

**Comment by lennondong** [comment]
Thanks for your reply. I'm trying to remove the podfile.lock file .
Another question : it took a lot of time to download files by cocoapods. Even up to 20 min it didn't finish downloading. 
...
Downloading dependencies
Using InAppSettingsKit (2.4.4)
Installing OpenWebRTC 0.1.4 (was 0.1.4)
...
-----------------

Besides.I'm not sure what are useful for SimpleDemo and what aren't according to https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC .

**Comment by superdump** [comment]
We're going to make a release very soon and then there will be a downloadable package you can install and start working on iOS applications. For now, apart from the apps that use cocoapods, you will need to build for OS X and then for iOS. All the information is on that wiki page.

I don't know why your download of the cocoapods is slow. it normally goes quite quickly for me, but then it will depend on your connection.

**Comment by lennondong** [comment]
Toady I spent 8 hours trying to solve all the errors of the two projects. So far none is running successfully. The SimpleDemo is not simple. 

Would you mind telling me how soon will you make a new release?

**Comment by superdump** [comment]
Hopefully tomorrow. If not, early next week.

**Comment by lennondong** [comment]
Thanks for your work! Good luck!

**Comment by lennondong** [comment]
Running into new questions as followed:

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_OpenWebRTCSettings", referenced from:
      objc-class-ref in VideoViewController.o
  "_OBJC_CLASS_$_OpenWebRTC", referenced from:
      objc-class-ref in AppDelegate.o
  "_OBJC_CLASS_$_OpenWebRTCNativeHandler", referenced from:
      objc-class-ref in VideoViewController.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by superdump** [comment]
@stefanalund ?

**Comment by stefanalund** [comment]
@lennondong any way you can share the project files? CocoaPods is not that easy to debug unfortunately.

**Comment by lennondong** [comment]
@stefanalund OK. How can I share the project with you ? by Email?

**Comment by lennondong** [comment]
NativeDemo   -  other errors:

1 if running the demo on iPhone4s 7.X device, it crashes.

dyld`dyld_fatal_error:
0x8fe3f084:  int3   
0x8fe3f085:  nop

It can running on iPhone4s 8.X simulator.  So the demo is just support for iOS 8.X later?

2 The demo can't running on iPad 8.X device. Here's the error.

![snip20150424_4](https://cloud.githubusercontent.com/assets/3203702/7313838/7173be14-ea90-11e4-8077-c96d5f9d8467.png)

**Comment by stefanalund** [comment]
@lennondong easiest is to put it in a new repo here on GitHub. Thanks!

**Comment by stefanalund** [comment]
@lennondong now I'm confused. Can you run it on an iPhone 4s? That means you can now build the ap, or?

Should be possible to set iOS 7.x as target as well, there is no hard requirement on iOS 8 as far as I know.

**Comment by lennondong** [comment]
@stefanalund  Just running well on simulator.  It can't run on iPhone4s and iPad.

**Comment by lennondong** [comment]
@stefanalund

  dyld: Symbol not found: _UIApplicationOpenSettingsURLString
  Referenced from: /var/mobile/Applications/61CF48F3-BC6C-45A2-AE35-5058BE1D8636/NativeDemo.app/NativeDemo
  Expected in: /System/Library/Frameworks/UIKit.framework/UIKit
 in /var/mobile/Applications/61CF48F3-BC6C-45A2-AE35-5058BE1D8636/NativeDemo.app/NativeDemo

**Comment by lennondong** [comment]
Thank you !  And I give it up. I have nothing to say.

**Comment by lennondong** [comment]
Do you know this?
UIApplicationOpenSettingsURLString was added in iOS 8 so you can't use it with iOS 7. There is no way to launch the app's portion of the Settings app in iOS 7.

So that's why NativeDemo can't run on my iPhone4s 7.X .

![image](https://cloud.githubusercontent.com/assets/3203702/7315502/a138b360-eaa0-11e4-803f-2818f72b46cf.png)


![snip20150424_4](https://cloud.githubusercontent.com/assets/3203702/7315500/9d258ff0-eaa0-11e4-8f5d-ecc456aee4c2.png)

**Comment by lennondong** [comment]
Now it can run on Iphone4s successfully.
But for iPad，how to solve the errors:
owr_init(NULL);   Implicit declaration of function 'owr_init' is invalid in C99;
owr_run_in_background();   Implicit declaration of function 'owr_run_in_background' is invalid in C99;

Another question:

When iPhone4s was connected with web client (http://demo.openwebrtc.io:38080/),there's  obvious network latency.

**Comment by stefanalund** [comment]
@lennondong The iPhone 4s is a bit old and we need to do some more optimizations, especially on the video side. What type of iPad do you use?

**Comment by superdump** [comment]
The fact that it thinks the calls to `owr_init()` and `owr_run_in_background()` are implicit declarations means that the OpenWebRTC framework is not being found, or the header files within it are not being found. This needs to be addressed before you will get any further.

**Comment by lennondong** [comment]
Thanks! I just solve the errors when running on iPad. 
New questions:
You're right. The speed between iPad and web client is higner than iPhone4s's. 
However , iPad failed to connect with iPhone4s .  What's wrong?

**Comment by lennondong** [comment]
![44](https://cloud.githubusercontent.com/assets/3203702/7316937/e8155fec-eaad-11e4-846e-5e04d51f6430.png)
