### ISSUE TITLE
x86_64/glibconfig.h file not found on NativeDemo when building for simulator

### ISSUE THREAD

**Issue by markmacau** [EricssonResearch/openwebrtc-examples#79]
Hi,

I got an error "x86_64/glibconfig.h" file not found when I try to build NativeDemo.

Here is what I did. Can anybody tell me what's wrong?

0. Environment
Mac OS Yosemite 10.10.2 on MacBook Pro
Xcode Version 6.3.1 (6D1002)

1. git clone
penwebrtc-examples and openwebrtc-ios-sdk are in my working directory.

2. cd to ios/NativeDemo
cd openwebrtc-examples/ios/NativeDemo/

3. run pod install
pod install

4. run xcode
open NativeDemo.xcworkspace

5. press build button
![screen shot 2015-04-23 at 11 21 20 pm](https://cloud.githubusercontent.com/assets/11770197/7299227/8acdb328-ea0f-11e4-9c19-a43d3fb11ff6.png)

**Comment by markmacau** [comment]
It works when I changed build target to a real device instead of Simulator.

**Comment by manuroe** [comment]
Is it possible to reopen the issue?
Xcode tests use the iOS simulator. It would be nice if the iOS OpenWebRTC framework does not break the iOS app automatic testing.

**Comment by magaton** [comment]
Hi,  I am facing the same problem (Yosemite, 10.10.3, XCode, 6.3.1). Is there any solution for this?

**Comment by superdump** [comment]
@magaton - run it on a device.

**Comment by Basscord** [comment]
@superdump, I'm a huge fan of your work here.

I'm attempting to upload a working example to iTunes connect for TestFlight distribution, but iTunes Connect doesn't seem to accept the build because of the simulator issue.

Is there a workaround? It works great on real devices.

**Comment by adrianbg** [comment]
Has anyone made headway on this issue? I don't have an iOS device yet so running on real hardware isn't an option for me :)

**Comment by stefanalund** [comment]
@superdump @EricssonResearch/non-ericsson-research-contributors do you know why x86 (and thus Simulator) support is not provided by Cerbero?

**Comment by adrianbg** [comment]
Only the 64-bit glibconfig header is missing. I'm trying to get i386 to work.

**Comment by adrianbg** [comment]
Forcing i386 instead of x86_64 makes it work for me. Seems like the only fix needed might be to generate the missing header file. Anyway, here's my workaround:

xcodebuild -workspace NativeDemo.xcworkspace -scheme NativeDemo -sdk iphonesimulator9.0 VALID_ARCHS="i386" -destination platform='iOS Simulator',OS=9.0,name='iPhone Retina (4-inch)'
xcrun instruments -w "iPhone 6s Plus (9.0)" -t Blank
xcrun simctl install booted <.app file generated by build>
xcrun simctl launch booted com.ericsson.research.owr.NativeDemo

**Comment by adrianbg** [comment]
Easier workaround: in NativeDemo build settings, show all settings then set both "Architectures" and "Valid Architectures" to i386.

**Comment by stefanalund** [comment]
Nice @adrianbg. Do you mind submitting a PR?

**Comment by adrianbg** [comment]
Unfortunately I don't think this is a commit-worthy solution. I've been removing all the other architectures which would interfere with building for an actual iOS device.

**Comment by ai-rex** [comment]
In Xcode 7.0, it seems that iPhone 6s Simulator can only run code built in x86_64, but the OpenWebRTC framework does not support x86_64. 

The easiest way is to run your code in iPhone 4s Simulator. This works for me.

**Comment by sdroege** [comment]
You just should need to add x86-64 to config/cross-ios-universal.cbc in cerbero. Then it should a) include that header and b) actually build all the stuff for x86-64 too.

**Comment by stefanalund** [comment]
@sdroege is that something we can fix by just updating the build instructions on the wiki? https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC

**Comment by sdroege** [comment]
See above commit, that should fix it.

**Comment by sdroege** [comment]
@superdump @stefanalund  Let me know if I should merge that commit

**Comment by stefanalund** [comment]
@sdroege thought you already did :smile: anyway, please do!

**Comment by sdroege** [comment]
Done

**Comment by stefanalund** [comment]
This fix is now available in version `0.39.0`. Closing.

**Comment by superdump** [comment]
`0.3.90` of the OpenWebRTC pod.
