### ISSUE TITLE
IOS NativeDemo pod warnings - CocoaPods was not able to update the `master` repo

### ISSUE THREAD

**Issue by KerwinMa** [EricssonResearch/openwebrtc-examples#87]
Mac OS X 10.10.1
1. git clone from https://github.com/EricssonResearch/openwebrtc-examples
2. git clone the ios-sdk to the folder
3. in NativeDemo folder, remove .lock file and run pod setup
4. pod install 
I got the following warnings:

Analyzing dependencies
Fetching podspec for `OpenWebRTC-SDK` from `../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`
Downloading dependencies
Installing InAppSettingsKit (2.4.4)
Installing OpenWebRTC (0.1.1)
Installing OpenWebRTC-SDK (0.1.1)
Generating Pods project
Integrating client project
[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

[!] Unable to read the license file `/Users/kerwin.ma/openwebrtc-examples/ios/NativeDemo/Pods/OpenWebRTC/LICENSE` for the spec `OpenWebRTC (0.1.1)`

[!] Unable to read the license file `/Users/kerwin.ma/openwebrtc-examples/ios/NativeDemo/Pods/OpenWebRTC/LICENSE` for the spec `OpenWebRTC (0.1.1)`

[!] Unable to read the license file `/Users/kerwin.ma/openwebrtc-examples/ios/NativeDemo/Pods/OpenWebRTC/LICENSE` for the spec `OpenWebRTC (0.1.1)`

[!] Unable to read the license file `/Users/kerwin.ma/openwebrtc-examples/ios/NativeDemo/Pods/OpenWebRTC/LICENSE` for the spec `OpenWebRTC (0.1.1)`

**Comment by stefanalund** [comment]
This issue is not specific to the OpenWebRTC pod. Seems like your computer cannot access the official pod trunk:
> [!] CocoaPods was not able to update the master repo. If this is an unexpected issue and persists you can inspect it running pod repo update --verbose

Because of this, you can't fetch the latest `OpenWebRTC` pod which as version 0.3.0. Try follow the instruction of running `pod repo update --verbose` again.

**Comment by stefanalund** [comment]
Feel free to re-open this issue if you have problem with the OpenWebRTC pod. Thanks.

**Comment by KerwinMa** [comment]
Hi @stefanalund, thanks for your help. I thought it would be our office firewall. I tried at home and I didn't remove the lock file this time, I got the following error:
localhost:NativeDemo kerwin.ma$ ls
NativeDemo		NativeDemo.xcworkspace	Podfile			README.md
NativeDemo.xcodeproj	NativeDemoTests		Podfile.lock
localhost:NativeDemo kerwin.ma$ pod install
Analyzing dependencies
Fetching podspec for `OpenWebRTC-SDK` from `../../../openwebrtc-ios-sdk/OpenWebRTC-SDK.podspec`
[!] Unable to satisfy the following requirements:

- `OpenWebRTC (= 0.3.0)` required by `Podfile.lock`
- `OpenWebRTC` required by `OpenWebRTC-SDK (0.1.1)`

Does it mean I get a wrong SDK version?

**Comment by superdump** [comment]
You need to update your openwebrtc-ios-sdk clone.

**Comment by KerwinMa** [comment]
Thanks @superdump, I cloned the master ios-sdk from https://github.com/EricssonResearch/openwebrtc-ios-sdk 
manually.

I ran the search with command
pod search OpenWebRTC


-> OpenWebRTC (0.1.1)
   OpenWebRTC.framework wrapped in CocoaPod
   pod 'OpenWebRTC', '~> 0.1.1'
   - Homepage: http://www.openwebrtc.io
   - Source:   http://static.verkstad.net/OpenWebRTC.framework_old.zip
   - Versions: 0.1.1, 0.1 [master repo]

No version 0.3.0 in repo.

**Comment by KerwinMa** [comment]
Seems my environment issue:
localhost:~ kerwin.ma$ pod setup
Setting up CocoaPods master repo
Setup completed

[!] CocoaPods was not able to update the `master` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

If I run 'pos repo update --verboss', it will say:localhost:~ kerwin.ma$ pod repo update --verbose

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  error: Your local changes to the following files would be overwritten by merge:
  	CocoaPods-version.yml
  	Specs/AdobeMobileSDK/4.4.0/AdobeMobileSDK.podspec.json
  	Specs/BugHD/1.1.0/BugHD.podspec.json
  	Specs/LlamaKit/0.6.0/LlamaKit.podspec.json
  	Specs/SynergyKIT-SDK-iOS/0.0.2/SynergyKIT-SDK-iOS.podspec.json
  	Specs/SynergyKIT-SDK-iOS/0.1.0/SynergyKIT-SDK-iOS.podspec.json
  	Specs/SynergyKIT-SDK-iOS/0.2.0/SynergyKIT-SDK-iOS.podspec.json
  	Specs/SynergyKIT-SDK-iOS/0.2.1/SynergyKIT-SDK-iOS.podspec.json
  	Specs/TestFlightSDK/0.8.3/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.0/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.1.beta1/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.1.beta2/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.1.beta3/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.1/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2.3.beta1/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2.4.beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2.4/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2.5/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2.6/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2.beta1/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2.beta2/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.2/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.3.0-beta.5/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.3.0-beta.6/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.3.0-beta.7/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.3.0.beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.3.0.beta2/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/1.3.0.beta4/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.0.2/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.0/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.1.1-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.1.2-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.1.3-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.1.3-noadid-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.1.3-noadid/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.1.3/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.1.4/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.2.0-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.2.0-noadid-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.2.1-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.2.1/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/2.2.3-beta/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/3.0.0/TestFlightSDK.podspec.json
  	Specs/TestFlightSDK/3.0.2/TestFlightSDK.podspec.json
  	Specs/UILabel-M5FillFrame/1.0.0/UILabel-M5FillFrame.podspec.json
  	Specs/UILabel-M5FillFrame/1.0.1/UILabel-M5FillFrame.podspec.json
  	Specs/XcodeEditor/1.0/XcodeEditor.podspec.json
  	Specs/XcodeEditor/1.1/XcodeEditor.podspec.json
  	Specs/XcodeEditor/1.2/XcodeEditor.podspec.json
  	Specs/XcodeEditor/1.3/XcodeEditor.podspec.json
  	Specs/XcodeEditor/1.4/XcodeEditor.podspec.json
  	Specs/XcodeEditor/1.5/XcodeEditor.podspec.json
  	Specs/XcodeEditor/1.6/XcodeEditor.podspec.json
  Please, commit your changes or stash them before you can merge.
  Aborting
  Updating 7c0f9e7..541b754

Should be my cocoaPods issue, not the SDK or Demo code issue.

**Comment by KerwinMa** [comment]
I think it would be that I had the old cocoaPods version installed and updated to a newer version later.
The following will help if anyone else has the same issue:
sudo rm -fr ~/Library/Caches/CocoaPods/ 
sudo rm -fr ~/.cocoapods/repos/master

pod setup
Setting up CocoaPods master repo

CocoaPods 0.37.0.rc.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Setup completed
localhost:~ kerwin.ma$ pod search OpenWebRTC


-> OpenWebRTC (0.3.0)
   OpenWebRTC.framework wrapped in a CocoaPod
   pod 'OpenWebRTC', '~> 0.3.0'
   - Homepage: http://www.openwebrtc.io
   - Source:   http://static.verkstad.net/OpenWebRTC_0.3.0.zip
   - Versions: 0.3.0, 0.1.4, 0.1.3, 0.1.2, 0.1.1, 0.1 [master repo]

Thanks.

**Comment by stefanalund** [comment]
Nice to hear that you found the problem, good to know for the future. Thanks.

**Comment by pomozoff** [comment]
@KerwinMa, thanks it works
