### ISSUE TITLE
How to select back camera in NativeDemo for iOS

### ISSUE THREAD

**Issue by tobi512** [EricssonResearch/openwebrtc-examples#94]
Hi everybody, 
first of all thanks for this awesome project, works much better on iOS than the official implementation!

I'm wondering how i can change the front camera used in NativeDemo by default to the back camera of my iDevice?! Can anybody tell me where this has to be done?

Cheers, 
Tobias

**Comment by superdump** [comment]
The webrtc.org implementation is an implementation, OpenWebRTC is another. There is no official or unofficial implementation of the WebRTC standards.

@stefanalund can probably help with switching the camera.

**Comment by stefanalund** [comment]
The best example is in the demo app Selfie. There we switch camera based unser input. Hope that's what you are looking for.

**Comment by tobi512** [comment]
@superdump Sorry for calling webrtc.org the official implementation, just seemed like it to me...
@stefanalund Yes, thats what i'm looking for, i'll have a look at it. 

Thanks to both of you, great support in here :+1:

**Comment by superdump** [comment]
@tobi512 no problem. That's what happens if a project takes the name of a standard directly as their project name and registers such domain names for the project.

Feel free to respond more here if you get stuck.

**Comment by tobi512** [comment]
Hey guys, its me again. 
Spend the last 2 weeks on sth else and now i'm back on the project...

I took a look at the Selfie-app for camera-selection and saw that it doesn't use the iOS-SDK. So camera selection is only possible through the C-API at the moment? Would be great to just have a function like "selectCamera(int camID)" through the SDK since my project uses the SDK just like NativeDemo.

After playing around with the code from selfie i still couldn't make it work (@stefanalund  how is the OwrVideoRenderer where i can set the source linked to the VideoView?!), isn't there an easier way? I would only need the back camera of the iDevice, front camera is probably never used.

Thanks in advance!

**Comment by tobi512** [comment]
After a bit of searching I found the right place to do it. For anyone interested, you have to add 
```
&& (g_strcmp0(name, "Back Camera") == 0)
```
to the if-condition in line 1044 (got_local_sources) of OpenWebRTCNativeHandler.m (included in the SDK) to use the back camera.

However, a nice way to choose the camera via a method from the SDK itself would be appreciated! @superdump @stefanalund :wink:

**Comment by stefanalund** [comment]
We agree 😏
