### ISSUE TITLE
can we communicate between to ios NativeDemo

### ISSUE THREAD

**Issue by imadgit** [EricssonResearch/openwebrtc-examples#96]
hi I'm newer here i have already used NativeDemo and it was great.
now i would communicate between 2 Ios devices using local server (NodJs server ).
can any one help me.

**Comment by superdump** [comment]
Where are you stuck?

**Comment by imadgit** [comment]
to connect the 2 devices with my own server
i would know if i must add second button (call button ) in the NativeDemo like the web Demo?

**Comment by imadgit** [comment]
what i must change exactly to do it ?

**Comment by superdump** [comment]
You need to change the following address to point to your server and the appropriate port: https://github.com/EricssonResearch/openwebrtc-examples/blob/master/ios/NativeDemo/NativeDemo/NativeDemoViewController.m#L36

**Comment by imadgit** [comment]
thanks , and what about the call between 2 devices
when i enter a room id in the first device , and do the same thing in the second ,the second join the first immediately or what ?

**Comment by imadgit** [comment]
what i try to sad, if i must to add anther button to make call between ?

**Comment by superdump** [comment]
No. Once you have entered the room number and pressed Done, you should see a self-view and a grey remote view. Then at the bottom of the screen there is a Call button. When two people are in the room, the call button should be blue and you can press it to start the call.

**Comment by imadgit** [comment]
thanks Robert i'll try this, because i must connect to ipad , also make video chat between and ipad and tablet.

**Comment by imadgit** [comment]
thanks Robert i'll try this, because i must connect to ipad , also make video chat between and ipad and tablet.
