### ISSUE TITLE
using OpenWebRTC release 

### ISSUE THREAD

**Issue by imadgit** [EricssonResearch/openwebrtc-examples#97]
can anybody  help me to use  the pre-release in my xcode project.
thanks.

**Comment by superdump** [comment]
We should document this indeed. For OS X development, install the two packages for OS X. For iOS either install the package for iOS or use the cocoapod. More info about iOS here: https://github.com/EricssonResearch/openwebrtc-examples/wiki/Developing-iOS-apps

**Comment by imadgit** [comment]
I downloaded the release and my question is how i can install packages for
OS X and for iOS.
and thanks Robert

2015-05-16 6:53 GMT+00:00 Robert Swain <notifications@github.com>:

**Comment by stefanalund** [comment]
The simplest way to use the iOS release is through the iOS SDK: https://github.com/EricssonResearch/openwebrtc-ios-sdk. It has been used to build our native sample app NativeDemo: https://github.com/EricssonResearch/openwebrtc-examples/tree/master/ios/NativeDemo

**Comment by stefanalund** [comment]
For OS X we only have one simple sample app: https://github.com/EricssonResearch/openwebrtc-examples/tree/master/osx
